# Core runtime and terminal tools verified on 2026-09-22.
brew "node"
brew "atuin"
brew "bat"
brew "carapace"
brew "eza"
brew "fd"
brew "fzf"
brew "fzf-tab"
brew "git-delta"
brew "hyperfine"
brew "jq"
brew "lazygit"
brew "mise"
brew "ripgrep"
brew "starship"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# macOS applications and font used by the configuration.
cask "codex"
cask "flutter"
cask "font-udev-gothic-nf"
cask "ghostty"
cask "orbstack"
